# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultipleCardTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultipleCardTest
    pod 'RxSwift', '4.1.2'
    pod 'RxCocoa', '4.1.2'
    pod 'RxBluetoothKit', '5.1.0'
    pod 'SnapKit', '4.0.0'
    pod 'RealmSwift', '3.6.0'
    pod 'SwiftyBeaver', '1.6.0'
    pod 'Alamofire', '4.7.2'
    pod 'Fabric'
    pod 'Crashlytics'
end

